style:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/styles/**'

ci:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**'

content:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/content/**'

pages:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/pages/**'

component:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/components/**'

layout:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/layouts/**'

config:
  - changed-files:
      - any-glob-to-any-file:
          - '*.config.*'
          - 'astro.config.mjs'
          - 'wrangler.toml'
          - 'package.json'
          - 'tsconfig.json'

tests:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.test.*'
          - 'e2e/**'
          - 'playwright.config.ts'
          - 'vitest.config.ts'

security:
  - changed-files:
      - any-glob-to-any-file:
          - 'public/_headers'
          - '.github/SECURITY.md'
          - 'src/lib/auth.ts'
