name: Feature Request
description: Suggest a new feature or improvement
labels: ['enhancement']
assignees: ['beelzer']
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What would you like to see added or changed?
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why would this be useful? What problem does it solve?
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Mockups, examples from other sites, or any other details.
    validations:
      required: false
