name: PR Size

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  size-label:
    name: Size Label
    runs-on: ubuntu-latest
    steps:
      - uses: pascalgn/size-label-action@v0.5.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          sizes: >
            {
              "0":    "size/XS",
              "10":   "size/S",
              "50":   "size/M",
              "200":  "size/L",
              "800":  "size/XL"
            }
